### ISSUE TITLE
Connection refused from room-poker to orchestrator

### ISSUE THREAD

**Issue by alanh0vx** [alexander171294/web-poker#70]
Hello Alexander,

Thanks for your great work, I am trying to deploy by using docker-compose

```
version: "3.7"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 321654987
      MYSQL_DATABASE: poker
    ports:
      - 3306:3306

  apiServer:
    image: alexander171294/web-poker-api:latest
    environment:
      DB_URL: "jdbc:mysql://db:3306/poker"
      DB_USERNAME: root
      DB_PASSWORD: 321654987
    ports:
      - 8083:8083
    depends_on:
      - db


  orchestrator:
    image: alexander171294/web-poker-orchestrator
    environment:
      DB_URL: "jdbc:mysql://db:3306/poker"
      DB_USERNAME: root
      DB_PASSWORD: 321654987

    ports:
      - 8082:8082
      - 8045:8045
    depends_on:
      - db

  room-poker:
    image: alexander171294/web-poker-room
    environment:
      ORCHESTRATOR_IP: orchestrator
    ports:
      - 8081:8081
    depends_on:
      - orchestrator

  poker-client:
    image: alexander171294/web-poker-client
    ports:
      - 8080:80
```

But got some errors
```
room-poker_1    | 2021-09-15 05:17:01.592 ERROR 1 --- [       Thread-1] a.c.t.r.o.OrchestratorThread             : Connection IO Exception, orchestrator:8045
room-poker_1    | 
room-poker_1    | java.net.ConnectException: Connection refused (Connection refused)
room-poker_1    | 	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:na]
room-poker_1    | 	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[na:na]
room-poker_1    | 	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[na:na]
room-poker_1    | 	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[na:na]
room-poker_1    | 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[na:na]
room-poker_1    | 	at java.base/java.net.Socket.connect(Socket.java:609) ~[na:na]
room-poker_1    | 	at java.base/java.net.Socket.connect(Socket.java:558) ~[na:na]
room-poker_1    | 	at java.base/java.net.Socket.<init>(Socket.java:454) ~[na:na]
room-poker_1    | 	at java.base/java.net.Socket.<init>(Socket.java:231) ~[na:na]
room-poker_1    | 	at ar.com.tandilweb.room.orchestratorBridge.OrchestratorThread.createSocketConneciton(OrchestratorThread.java:137) ~[classes!/:0.0.1]
room-poker_1    | 	at ar.com.tandilweb.room.orchestratorBridge.OrchestratorThread.run(OrchestratorThread.java:85) ~[classes!/:0.0.1]
room-poker_1    | 	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
room-poker_1    | 
```
